version: "2.0"
services:
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ROCKET_PORT=8000
      - REDIS_ADDR=redis://redis:6379/
    ports:
      - "8000:8000"
    depends_on:
      - redis
  test_client:
    build:
      context: ./e2e_test/.
    environment:
      - PROXY_PORT=8000
    depends_on:
      - redis
      - proxy

  redis:
    image: redis
    ports:
      - "6379:6379"
